# Imports

In [109]:
import pandas as pd
import prince
from mlxtend.frequent_patterns import apriori, association_rules

# Loading the Binned Data

## Markdown Cells

In [110]:
md_filepath = 'binning-data/markdown_group_binned.csv'
md_df = pd.read_csv(md_filepath)

In [111]:
# save the original dataframe
md_original = md_df

In [112]:
# clear the first two columns
md_df = md_df.drop(['Unnamed: 0', 'nb_id'], axis = 1)

# change True and False to T and F
md_df = md_df.replace(True, 'T')
md_df = md_df.replace(False, 'F')

In [113]:
# initial look at the data
md_df.head()

,longer_beginning,longer_ending,has_author,has_equation,jupyter_prop,markdown_prop,num_contrib,image_prop,is_education,has_links,has_comments,md_frequency,has_title,num_commits,md_format,non_exec_prop,exec_inorder,exec_skips,has_error
0,T,F,F,F,medium,low,lower,low,T,T,F,low,T,lower,T,low,higher,lower,F
1,T,F,F,F,high,medium,lower,low,T,T,T,medium,F,lower,T,high,higher,lower,F
2,T,F,F,F,high,medium,lower,low,T,T,T,medium,T,lower,T,high,higher,lower,F
3,T,F,F,F,high,medium,lower,low,T,T,T,medium,T,lower,F,low,higher,lower,F
4,T,F,F,T,high,medium,lower,low,F,F,T,medium,F,lower,F,low,higher,lower,F

In [114]:
# extract the column titles
md_vars = list(md_df)
md_vars

['longer_beginning',
 'longer_ending',
 'has_author',
 'has_equation',
 'jupyter_prop',
 'markdown_prop',
 'num_contrib',
 'image_prop',
 'is_education',
 'has_links',
 'has_comments',
 'md_frequency',
 'has_title',
 'num_commits',
 'md_format',
 'non_exec_prop',
 'exec_inorder',
 'exec_skips',
 'has_error']

In [115]:
# check the bin sizes
for var in md_vars:
    print(md_df[var].value_counts())

T    1246
F    1045
Name: longer_beginning, dtype: int64
F    1698
T     593
Name: longer_ending, dtype: int64
F    2184
T     107
Name: has_author, dtype: int64
F    1847
T     444
Name: has_equation, dtype: int64
high      1804
medium     346
low        141
Name: jupyter_prop, dtype: int64
medium    1879
high       216
low        196
Name: markdown_prop, dtype: int64
lower     2140
higher     151
Name: num_contrib, dtype: int64
low       1241
medium     873
high       177
Name: image_prop, dtype: int64
T    1321
F     970
Name: is_education, dtype: int64
F    1423
T     868
Name: has_links, dtype: int64
T    2038
F     253
Name: has_comments, dtype: int64
medium    1276
high       660
low        355
Name: md_frequency, dtype: int64
T    1478
F     813
Name: has_title, dtype: int64
lower     1981
higher     310
Name: num_commits, dtype: int64
F    1236
T    1055
Name: md_format, dtype: int64
low       2003
high       173
medium     115
Name: non_exec_prop, dtype: int64
higher    2180
lower      111
Name: exec_inorder, dtype: int64
lower     1925
higher     366
Name: exec_skips, dtype: int64
F    1984
T     307
Name: has_error, dtype: int64

## No Markdown Cells

In [116]:
no_md_filepath = 'binning-data/no_markdown_group_binned.csv'
no_md_df = pd.read_csv(no_md_filepath)

In [117]:
# save the original dataframe
no_md_original = no_md_df

In [118]:
# clear the first two columns
no_md_df = no_md_df.drop(['Unnamed: 0', 'nb_id'], axis = 1)

# change True and False to T and F (strings)
no_md_df = no_md_df.replace(True, 'T')
no_md_df = no_md_df.replace(False, 'F')

In [119]:
# initial look at the data
no_md_df.head()

,has_author,jupyter_prop,num_contrib,image_prop,is_education,has_comments,num_commits,non_exec_prop,exec_inorder,exec_skips,has_error
0,F,medium,lower,low,F,F,lower,lower,higher,lower,F
1,F,high,lower,low,F,T,lower,lower,higher,lower,T
2,F,low,higher,low,F,T,higher,lower,higher,lower,F
3,F,high,lower,low,F,T,lower,lower,higher,lower,F
4,F,high,lower,low,F,T,higher,lower,higher,lower,T

In [120]:
# extract the column titles
no_md_vars = list(no_md_df)
no_md_vars

['has_author',
 'jupyter_prop',
 'num_contrib',
 'image_prop',
 'is_education',
 'has_comments',
 'num_commits',
 'non_exec_prop',
 'exec_inorder',
 'exec_skips',
 'has_error']

In [121]:
# check the bin counts
for var in no_md_vars:
    print(no_md_df[var].value_counts())

F    1343
T      12
Name: has_author, dtype: int64
high      910
medium    286
low       159
Name: jupyter_prop, dtype: int64
lower     1237
higher     118
Name: num_contrib, dtype: int64
low       916
medium    281
high      158
Name: image_prop, dtype: int64
F    1209
T     146
Name: is_education, dtype: int64
T    919
F    436
Name: has_comments, dtype: int64
lower     1042
higher     313
Name: num_commits, dtype: int64
lower     1249
higher     106
Name: non_exec_prop, dtype: int64
higher    1205
lower      150
Name: exec_inorder, dtype: int64
lower     1179
higher     176
Name: exec_skips, dtype: int64
F    1139
T     216
Name: has_error, dtype: int64

# Multiple Correspondence Analysis (MCA)

## Markdown Cells

### Performing MCA

In [122]:
# instantiate MCA object and fit to data
md_mca = prince.MCA(n_components = len(md_vars),
                   n_iter = 10,
                   copy = True,
                   check_input = True,
                   engine = 'auto',
                   random_state = 42)
md_mca_fit = md_mca.fit(md_df)

In [123]:
# put the results into dataframe format
md_mca_df = md_mca_fit.row_coordinates(md_df)

# initial look at the results of the MCA
md_mca_df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,0.038950,0.764150,0.123466,-0.573001,0.159412,-0.204294,0.304377,0.201377,-0.190293,0.129577,-0.185345,0.197234,-0.352195,-0.169324,-0.125456,0.142135,-0.402566,0.068305,-0.162917
1,0.379564,0.015330,0.418419,-0.186083,-0.246143,0.184833,-0.517825,0.400313,0.171027,-0.027436,-0.090247,-0.123177,-0.118447,0.201818,0.160676,0.159336,0.124330,0.098163,-0.293007
2,0.460085,-0.070535,0.408262,-0.265880,-0.238258,0.137878,-0.251149,0.324552,0.269962,-0.056728,-0.141259,-0.048566,0.010673,0.370292,0.096294,0.021593,0.078480,0.111308,-0.235359
3,0.154882,-0.208383,0.083654,-0.174085,-0.063831,0.149867,0.030867,0.029345,0.131944,-0.062887,-0.063892,-0.012680,-0.239903,0.131121,0.038304,0.005465,-0.221667,-0.075274,0.161511
4,-0.177197,-0.204644,0.069720,0.044641,0.069887,0.080545,-0.319025,-0.109154,-0.073152,0.135630,-0.120507,-0.000196,0.051243,0.148198,-0.058387,0.373835,-0.085053,-0.225825,0.103342

### Analyzing the Results of MCA

In [124]:
# extract the explained variance
md_mca_fit.explained_inertia_

[0.1264117646830074,
 0.07712189891928822,
 0.06526424818252895,
 0.05840604317218444,
 0.0565107247007416,
 0.04972328585655356,
 0.04611778026252358,
 0.043746856640539476,
 0.04271778486206097,
 0.04008643490669374,
 0.03888754395770909,
 0.03642054625134442,
 0.03497393600902581,
 0.03457026936060691,
 0.03392026746091107,
 0.032169249866233006,
 0.02933996114039189,
 0.028167206290571938,
 0.026366212871817868]

## No Markdown Cells

### Performing MCA

In [125]:
# instantiate MCA object and fit to data
no_md_mca = prince.MCA(n_components = len(no_md_vars),
                   n_iter = 10,
                   copy = True,
                   check_input = True,
                   engine = 'auto',
                   random_state = 42)
no_md_mca_fit = no_md_mca.fit(no_md_df)

In [126]:
# put the results into dataframe format
no_md_mca_df = no_md_mca_fit.row_coordinates(no_md_df)

# initial look at the results of the MCA
no_md_mca_df.head()

,0,1,2,3,4,5,6,7,8,9,10
0,-0.261743,0.296846,-0.257493,-0.137606,0.353145,-0.391610,-0.227178,0.040868,-0.173026,-0.182239,-0.107518
1,0.178250,0.041815,-0.228766,-0.335240,-0.239304,0.423842,0.295788,0.039632,0.048768,-0.293180,-0.113312
2,-0.406530,-0.122694,0.352174,0.712612,0.732707,0.570806,0.498620,0.231289,0.119264,-0.033058,0.198903
3,-0.131782,-0.086343,0.028920,-0.231080,-0.122400,0.103071,-0.011793,-0.073935,0.028024,-0.192888,-0.095841
4,0.285240,-0.023131,0.126216,-0.004104,-0.113840,0.465679,0.443982,0.076053,-0.161783,-0.182193,-0.188592

### Analyzing the Results of MCA

In [127]:
# extract the explained variance
no_md_mca_fit.explained_inertia_

[0.12370870341785964,
 0.09849552031983039,
 0.09734374536610015,
 0.08658594297883986,
 0.08400283383718782,
 0.07838450195841805,
 0.07407927250811161,
 0.07013650754422476,
 0.06622192784246521,
 0.05862806239954164,
 0.05692710063661963]

# Association Rule Mining

## One-Hot Encoding

We must put our categorical data into a format that can be input into the Apriori algorithm

### Markdown Cells

In [128]:
# create a copy of the dataframe that we will one-hot encode
md_one_hot = md_original.copy()

In [129]:
# drop the first two columns (since we took the original dataframe)
md_one_hot = md_one_hot.drop(['Unnamed: 0', 'nb_id'], axis = 1)

In [130]:
# extract the datatypes so we can isolate the variables that need dummies
list(enumerate(zip(md_vars, md_one_hot.dtypes)))

[(0, ('longer_beginning', dtype('bool'))),
 (1, ('longer_ending', dtype('bool'))),
 (2, ('has_author', dtype('bool'))),
 (3, ('has_equation', dtype('bool'))),
 (4, ('jupyter_prop', dtype('O'))),
 (5, ('markdown_prop', dtype('O'))),
 (6, ('num_contrib', dtype('O'))),
 (7, ('image_prop', dtype('O'))),
 (8, ('is_education', dtype('bool'))),
 (9, ('has_links', dtype('bool'))),
 (10, ('has_comments', dtype('bool'))),
 (11, ('md_frequency', dtype('O'))),
 (12, ('has_title', dtype('bool'))),
 (13, ('num_commits', dtype('O'))),
 (14, ('md_format', dtype('bool'))),
 (15, ('non_exec_prop', dtype('O'))),
 (16, ('exec_inorder', dtype('O'))),
 (17, ('exec_skips', dtype('O'))),
 (18, ('has_error', dtype('bool')))]

In [131]:
# extract t/f vars
md_tf_vars = [md_vars[i] for i in [0, 1, 2, 3, 8, 9, 10, 12, 14, 18]]
md_tf_vars

['longer_beginning',
 'longer_ending',
 'has_author',
 'has_equation',
 'is_education',
 'has_links',
 'has_comments',
 'has_title',
 'md_format',
 'has_error']

In [132]:
# extract non-t/f vars
md_s_vars = [md_vars[i] for i in [4, 5, 6, 7, 11, 13, 15, 16, 17]]
md_s_vars

['jupyter_prop',
 'markdown_prop',
 'num_contrib',
 'image_prop',
 'md_frequency',
 'num_commits',
 'non_exec_prop',
 'exec_inorder',
 'exec_skips']

In [133]:
# extract value counts so we can isolate variables that have 3 bins
for (i, var) in enumerate(md_s_vars):
    print(i, md_one_hot[var].value_counts())

0 high      1804
medium     346
low        141
Name: jupyter_prop, dtype: int64
1 medium    1879
high       216
low        196
Name: markdown_prop, dtype: int64
2 lower     2140
higher     151
Name: num_contrib, dtype: int64
3 low       1241
medium     873
high       177
Name: image_prop, dtype: int64
4 medium    1276
high       660
low        355
Name: md_frequency, dtype: int64
5 lower     1981
higher     310
Name: num_commits, dtype: int64
6 low       2003
high       173
medium     115
Name: non_exec_prop, dtype: int64
7 higher    2180
lower      111
Name: exec_inorder, dtype: int64
8 lower     1925
higher     366
Name: exec_skips, dtype: int64

In [134]:
# extract lower/higher variables
md_lh_vars = [md_s_vars[i] for i in [2, 5, 7, 8]]

In [135]:
# extract low/medium/high variables
md_lmh_vars = [md_s_vars[i] for i in [0, 1, 3, 4, 6]]

In [136]:
# turn t/f vars into 1/0
for tf_var in md_tf_vars:
    md_one_hot[tf_var] = md_one_hot[tf_var].replace(True, 1)
    md_one_hot[tf_var] = md_one_hot[tf_var].replace(False, 0)

In [137]:
# turn lower/higher vars into 1/0
for lh_var in md_lh_vars:
    md_one_hot[lh_var] = md_one_hot[lh_var].replace('higher', 1)
    md_one_hot[lh_var] = md_one_hot[lh_var].replace('lower', 0)

In [138]:
# create dataframe that will hold all of the dummy variables
md_one_hot_cols = pd.get_dummies(md_one_hot[md_lmh_vars])

# initial look at the dummy variables
md_one_hot_cols.head()

,jupyter_prop_high,jupyter_prop_low,jupyter_prop_medium,markdown_prop_high,markdown_prop_low,markdown_prop_medium,image_prop_high,image_prop_low,image_prop_medium,md_frequency_high,md_frequency_low,md_frequency_medium,non_exec_prop_high,non_exec_prop_low,non_exec_prop_medium
0,0,0,1,0,1,0,0,1,0,0,1,0,0,1,0
1,1,0,0,0,0,1,0,1,0,0,0,1,1,0,0
2,1,0,0,0,0,1,0,1,0,0,0,1,1,0,0
3,1,0,0,0,0,1,0,1,0,0,0,1,0,1,0
4,1,0,0,0,0,1,0,1,0,0,0,1,0,1,0

In [139]:
# delete the original columns from the one-hot dataframe
md_one_hot = md_one_hot.drop(md_lmh_vars, axis = 1)

# join the one hot dataframe with the dummy dataframe
md_one_hot = pd.concat([md_one_hot, md_one_hot_cols], axis = 1)

In [140]:
# initial look at the one-hot encoded data
md_one_hot.head()

,longer_beginning,longer_ending,has_author,has_equation,num_contrib,is_education,has_links,has_comments,has_title,num_commits,...,markdown_prop_medium,image_prop_high,image_prop_low,image_prop_medium,md_frequency_high,md_frequency_low,md_frequency_medium,non_exec_prop_high,non_exec_prop_low,non_exec_prop_medium
0,1.0,0.0,0.0,0.0,0,1.0,1.0,0.0,1.0,0,...,0,0,1,0,0,1,0,0,1,0
1,1.0,0.0,0.0,0.0,0,1.0,1.0,1.0,0.0,0,...,1,0,1,0,0,0,1,1,0,0
2,1.0,0.0,0.0,0.0,0,1.0,1.0,1.0,1.0,0,...,1,0,1,0,0,0,1,1,0,0
3,1.0,0.0,0.0,0.0,0,1.0,1.0,1.0,1.0,0,...,1,0,1,0,0,0,1,0,1,0
4,1.0,0.0,0.0,1.0,0,0.0,0.0,1.0,0.0,0,...,1,0,1,0,0,0,1,0,1,0

In [141]:
# convert everything to an int type
for var in list(md_one_hot):
    md_one_hot[var] = md_one_hot[var].astype(int)

In [142]:
# check the datatypes
md_one_hot.dtypes

longer_beginning        int64
longer_ending           int64
has_author              int64
has_equation            int64
num_contrib             int64
is_education            int64
has_links               int64
has_comments            int64
has_title               int64
num_commits             int64
md_format               int64
exec_inorder            int64
exec_skips              int64
has_error               int64
jupyter_prop_high       int64
jupyter_prop_low        int64
jupyter_prop_medium     int64
markdown_prop_high      int64
markdown_prop_low       int64
markdown_prop_medium    int64
image_prop_high         int64
image_prop_low          int64
image_prop_medium       int64
md_frequency_high       int64
md_frequency_low        int64
md_frequency_medium     int64
non_exec_prop_high      int64
non_exec_prop_low       int64
non_exec_prop_medium    int64
dtype: object

### No Markdown Cells

In [143]:
# copy the original dataframe
no_md_one_hot = no_md_original.copy()

In [144]:
# drop the first two columns
no_md_one_hot = no_md_one_hot.drop(['Unnamed: 0', 'nb_id'], axis = 1)

In [145]:
# extract datatypes
list(enumerate(zip(no_md_vars, no_md_one_hot.dtypes)))

[(0, ('has_author', dtype('bool'))),
 (1, ('jupyter_prop', dtype('O'))),
 (2, ('num_contrib', dtype('O'))),
 (3, ('image_prop', dtype('O'))),
 (4, ('is_education', dtype('bool'))),
 (5, ('has_comments', dtype('bool'))),
 (6, ('num_commits', dtype('O'))),
 (7, ('non_exec_prop', dtype('O'))),
 (8, ('exec_inorder', dtype('O'))),
 (9, ('exec_skips', dtype('O'))),
 (10, ('has_error', dtype('bool')))]

In [146]:
# extract t/f vars
no_md_tf_vars = [no_md_vars[i] for i in [0, 4, 5, 10]]
no_md_tf_vars

['has_author', 'is_education', 'has_comments', 'has_error']

In [147]:
# extract non-tf vars
no_md_s_vars = [no_md_vars[i] for i in [1, 2, 3, 6, 7, 8, 9]]
no_md_s_vars

['jupyter_prop',
 'num_contrib',
 'image_prop',
 'num_commits',
 'non_exec_prop',
 'exec_inorder',
 'exec_skips']

In [148]:
# extract value counts
for (i, var) in enumerate(no_md_s_vars):
    print(i, no_md_one_hot[var].value_counts())

0 high      910
medium    286
low       159
Name: jupyter_prop, dtype: int64
1 lower     1237
higher     118
Name: num_contrib, dtype: int64
2 low       916
medium    281
high      158
Name: image_prop, dtype: int64
3 lower     1042
higher     313
Name: num_commits, dtype: int64
4 lower     1249
higher     106
Name: non_exec_prop, dtype: int64
5 higher    1205
lower      150
Name: exec_inorder, dtype: int64
6 lower     1179
higher     176
Name: exec_skips, dtype: int64

In [149]:
# extract lower/higher vars
no_md_lh_vars = [no_md_s_vars[i] for i in [1, 3, 4, 5, 6]]

In [150]:
# extract low/medium/high vars
no_md_lmh_vars = [no_md_s_vars[i] for i in [0, 2]]

In [151]:
# turn t/f vars into 1/0
for tf_var in no_md_tf_vars:
    no_md_one_hot[tf_var] = no_md_one_hot[tf_var].replace(True, 1)
    no_md_one_hot[tf_var] = no_md_one_hot[tf_var].replace(False, 0)

In [152]:
# turn lower/higher vars into 1/0
for lh_var in no_md_lh_vars:
    no_md_one_hot[lh_var] = no_md_one_hot[lh_var].replace('higher', 1)
    no_md_one_hot[lh_var] = no_md_one_hot[lh_var].replace('lower', 0)

In [153]:
# create dataframe that will hold dummy vars
no_md_one_hot_cols = pd.get_dummies(no_md_one_hot[no_md_lmh_vars])

# initial look at the dummy variables
no_md_one_hot_cols.head()

,jupyter_prop_high,jupyter_prop_low,jupyter_prop_medium,image_prop_high,image_prop_low,image_prop_medium
0,0,0,1,0,1,0
1,1,0,0,0,1,0
2,0,1,0,0,1,0
3,1,0,0,0,1,0
4,1,0,0,0,1,0

In [154]:
# delete the original columns from the one-hot dataframe
no_md_one_hot = no_md_one_hot.drop(no_md_lmh_vars, axis = 1)

# join the one hot dataframe w the dummy vars
no_md_one_hot = pd.concat([no_md_one_hot, no_md_one_hot_cols], axis = 1)

In [155]:
# initial look at the one-hot encoded data
no_md_one_hot.head()

,has_author,num_contrib,is_education,has_comments,num_commits,non_exec_prop,exec_inorder,exec_skips,has_error,jupyter_prop_high,jupyter_prop_low,jupyter_prop_medium,image_prop_high,image_prop_low,image_prop_medium
0,0.0,0,0.0,0.0,0,0,1,0,0.0,0,0,1,0,1,0
1,0.0,0,0.0,1.0,0,0,1,0,1.0,1,0,0,0,1,0
2,0.0,1,0.0,1.0,1,0,1,0,0.0,0,1,0,0,1,0
3,0.0,0,0.0,1.0,0,0,1,0,0.0,1,0,0,0,1,0
4,0.0,0,0.0,1.0,1,0,1,0,1.0,1,0,0,0,1,0

In [156]:
# convert everything to an int type
for var in list(no_md_one_hot):
    no_md_one_hot[var] = no_md_one_hot[var].astype(int)

In [157]:
# check the datatypes
no_md_one_hot.dtypes

has_author             int64
num_contrib            int64
is_education           int64
has_comments           int64
num_commits            int64
non_exec_prop          int64
exec_inorder           int64
exec_skips             int64
has_error              int64
jupyter_prop_high      int64
jupyter_prop_low       int64
jupyter_prop_medium    int64
image_prop_high        int64
image_prop_low         int64
image_prop_medium      int64
dtype: object

## Performing the Apriori Algorithm

### Markdown Cells

In [158]:
# requires True/False instead of 1/0
md_one_hot = md_one_hot.replace(1, True)
md_one_hot = md_one_hot.replace(0, False)

In [159]:
# initial look at the data
md_one_hot.head()

,longer_beginning,longer_ending,has_author,has_equation,num_contrib,is_education,has_links,has_comments,has_title,num_commits,...,markdown_prop_medium,image_prop_high,image_prop_low,image_prop_medium,md_frequency_high,md_frequency_low,md_frequency_medium,non_exec_prop_high,non_exec_prop_low,non_exec_prop_medium
0,True,False,False,False,False,True,True,False,True,False,...,False,False,True,False,False,True,False,False,True,False
1,True,False,False,False,False,True,True,True,False,False,...,True,False,True,False,False,False,True,True,False,False
2,True,False,False,False,False,True,True,True,True,False,...,True,False,True,False,False,False,True,True,False,False
3,True,False,False,False,False,True,True,True,True,False,...,True,False,True,False,False,False,True,False,True,False
4,True,False,False,True,False,False,False,True,False,False,...,True,False,True,False,False,False,True,False,True,False

In [160]:
# perform the apriori algorithm on the dataframe
md_itemsets = apriori(md_one_hot, min_support = 0.5, use_colnames = True)

# look at the itemsets
md_itemsets

     support                                           itemsets
0   0.543867                                 (longer_beginning)
1   0.576604                                     (is_education)
2   0.889568                                     (has_comments)
3   0.645133                                        (has_title)
4   0.951550                                     (exec_inorder)
5   0.787429                                (jupyter_prop_high)
6   0.820166                             (markdown_prop_medium)
7   0.541685                                   (image_prop_low)
8   0.556962                              (md_frequency_medium)
9   0.874291                                (non_exec_prop_low)
10  0.503274                   (longer_beginning, has_comments)
11  0.516368                   (longer_beginning, exec_inorder)
12  0.516805                       (has_comments, is_education)
13  0.548669                       (is_education, exec_inorder)
14  0.574422                          (has_comments, has_title)
15  0.848101                       (has_comments, exec_inorder)
16  0.700131                  (has_comments, jupyter_prop_high)
17  0.736796               (markdown_prop_medium, has_comments)
18  0.774771                  (has_comments, non_exec_prop_low)
19  0.621126                          (has_title, exec_inorder)
20  0.505020                     (has_title, jupyter_prop_high)
21  0.530336                  (markdown_prop_medium, has_title)
22  0.566565                     (has_title, non_exec_prop_low)
23  0.750764                  (exec_inorder, jupyter_prop_high)
24  0.780882               (markdown_prop_medium, exec_inorder)
25  0.520297                     (image_prop_low, exec_inorder)
26  0.528154                (exec_inorder, md_frequency_medium)
27  0.829769                  (exec_inorder, non_exec_prop_low)
28  0.664339          (markdown_prop_medium, jupyter_prop_high)
29  0.686163             (jupyter_prop_high, non_exec_prop_low)
30  0.720210          (markdown_prop_medium, non_exec_prop_low)
31  0.553907            (has_comments, has_title, exec_inorder)
32  0.503274       (has_comments, has_title, non_exec_prop_low)
33  0.668704    (has_comments, exec_inorder, jupyter_prop_high)
34  0.703623  (markdown_prop_medium, has_comments, exec_inor...
35  0.737233    (has_comments, exec_inorder, non_exec_prop_low)
36  0.596683  (markdown_prop_medium, has_comments, jupyter_p...
37  0.609777  (has_comments, jupyter_prop_high, non_exec_pro...
38  0.644697  (markdown_prop_medium, has_comments, non_exec_...
39  0.510258    (markdown_prop_medium, has_title, exec_inorder)
40  0.545613       (has_title, exec_inorder, non_exec_prop_low)
41  0.634221  (markdown_prop_medium, exec_inorder, jupyter_p...
42  0.652117  (jupyter_prop_high, exec_inorder, non_exec_pro...
43  0.683544  (markdown_prop_medium, exec_inorder, non_exec_...
44  0.580969  (markdown_prop_medium, jupyter_prop_high, non_...
45  0.570930  (markdown_prop_medium, has_comments, exec_inor...
46  0.580969  (has_comments, jupyter_prop_high, exec_inorder...
47  0.614142  (markdown_prop_medium, has_comments, exec_inor...
48  0.521170  (markdown_prop_medium, has_comments, jupyter_p...
49  0.552597  (markdown_prop_medium, jupyter_prop_high, exec...

In [161]:
# add a column that counts the number of elements in the itemset
md_itemsets['length'] = md_itemsets['itemsets'].apply(lambda x : len(x))
md_itemsets

     support                                           itemsets  length
0   0.543867                                 (longer_beginning)       1
1   0.576604                                     (is_education)       1
2   0.889568                                     (has_comments)       1
3   0.645133                                        (has_title)       1
4   0.951550                                     (exec_inorder)       1
5   0.787429                                (jupyter_prop_high)       1
6   0.820166                             (markdown_prop_medium)       1
7   0.541685                                   (image_prop_low)       1
8   0.556962                              (md_frequency_medium)       1
9   0.874291                                (non_exec_prop_low)       1
10  0.503274                   (longer_beginning, has_comments)       2
11  0.516368                   (longer_beginning, exec_inorder)       2
12  0.516805                       (has_comments, is_education)       2
13  0.548669                       (is_education, exec_inorder)       2
14  0.574422                          (has_comments, has_title)       2
15  0.848101                       (has_comments, exec_inorder)       2
16  0.700131                  (has_comments, jupyter_prop_high)       2
17  0.736796               (markdown_prop_medium, has_comments)       2
18  0.774771                  (has_comments, non_exec_prop_low)       2
19  0.621126                          (has_title, exec_inorder)       2
20  0.505020                     (has_title, jupyter_prop_high)       2
21  0.530336                  (markdown_prop_medium, has_title)       2
22  0.566565                     (has_title, non_exec_prop_low)       2
23  0.750764                  (exec_inorder, jupyter_prop_high)       2
24  0.780882               (markdown_prop_medium, exec_inorder)       2
25  0.520297                     (image_prop_low, exec_inorder)       2
26  0.528154                (exec_inorder, md_frequency_medium)       2
27  0.829769                  (exec_inorder, non_exec_prop_low)       2
28  0.664339          (markdown_prop_medium, jupyter_prop_high)       2
29  0.686163             (jupyter_prop_high, non_exec_prop_low)       2
30  0.720210          (markdown_prop_medium, non_exec_prop_low)       2
31  0.553907            (has_comments, has_title, exec_inorder)       3
32  0.503274       (has_comments, has_title, non_exec_prop_low)       3
33  0.668704    (has_comments, exec_inorder, jupyter_prop_high)       3
34  0.703623  (markdown_prop_medium, has_comments, exec_inor...       3
35  0.737233    (has_comments, exec_inorder, non_exec_prop_low)       3
36  0.596683  (markdown_prop_medium, has_comments, jupyter_p...       3
37  0.609777  (has_comments, jupyter_prop_high, non_exec_pro...       3
38  0.644697  (markdown_prop_medium, has_comments, non_exec_...       3
39  0.510258    (markdown_prop_medium, has_title, exec_inorder)       3
40  0.545613       (has_title, exec_inorder, non_exec_prop_low)       3
41  0.634221  (markdown_prop_medium, exec_inorder, jupyter_p...       3
42  0.652117  (jupyter_prop_high, exec_inorder, non_exec_pro...       3
43  0.683544  (markdown_prop_medium, exec_inorder, non_exec_...       3
44  0.580969  (markdown_prop_medium, jupyter_prop_high, non_...       3
45  0.570930  (markdown_prop_medium, has_comments, exec_inor...       4
46  0.580969  (has_comments, jupyter_prop_high, exec_inorder...       4
47  0.614142  (markdown_prop_medium, has_comments, exec_inor...       4
48  0.521170  (markdown_prop_medium, has_comments, jupyter_p...       4
49  0.552597  (markdown_prop_medium, jupyter_prop_high, exec...       4

In [162]:
# filter down to itemsets that have at least 2 items and at least 0.7 support
md_itemsets[(md_itemsets['length'] >= 2) & (md_itemsets['support'] >= 0.7)]

     support                                           itemsets  length
15  0.848101                       (has_comments, exec_inorder)       2
16  0.700131                  (has_comments, jupyter_prop_high)       2
17  0.736796               (markdown_prop_medium, has_comments)       2
18  0.774771                  (has_comments, non_exec_prop_low)       2
23  0.750764                  (exec_inorder, jupyter_prop_high)       2
24  0.780882               (markdown_prop_medium, exec_inorder)       2
27  0.829769                  (exec_inorder, non_exec_prop_low)       2
30  0.720210          (markdown_prop_medium, non_exec_prop_low)       2
34  0.703623  (markdown_prop_medium, has_comments, exec_inor...       3
35  0.737233    (has_comments, exec_inorder, non_exec_prop_low)       3

### No Markdown Cells

In [163]:
# replace 1/0 with True/False
no_md_one_hot = no_md_one_hot.replace(1, True)
no_md_one_hot = no_md_one_hot.replace(0, False)

In [164]:
# initial look at the data
no_md_one_hot.head()

,has_author,num_contrib,is_education,has_comments,num_commits,non_exec_prop,exec_inorder,exec_skips,has_error,jupyter_prop_high,jupyter_prop_low,jupyter_prop_medium,image_prop_high,image_prop_low,image_prop_medium
0,False,False,False,False,False,False,True,False,False,False,False,True,False,True,False
1,False,False,False,True,False,False,True,False,True,True,False,False,False,True,False
2,False,True,False,True,True,False,True,False,False,False,True,False,False,True,False
3,False,False,False,True,False,False,True,False,False,True,False,False,False,True,False
4,False,False,False,True,True,False,True,False,True,True,False,False,False,True,False

In [165]:
# perform apriori algorithm on the dataframe
no_md_itemsets = apriori(no_md_one_hot, min_support = 0.5, use_colnames = True)

# look at the itemsets
no_md_itemsets

    support                           itemsets
0  0.678229                     (has_comments)
1  0.889299                     (exec_inorder)
2  0.671587                (jupyter_prop_high)
3  0.676015                   (image_prop_low)
4  0.597048       (has_comments, exec_inorder)
5  0.602214  (exec_inorder, jupyter_prop_high)
6  0.611070     (image_prop_low, exec_inorder)

Not a lot of itemsets (probably because not a lot of variables), maybe reduce `min_support`?

In [166]:
# add a column that counts the number of elements in the itemset
no_md_itemsets['length'] = no_md_itemsets['itemsets'].apply(lambda x : len(x))
no_md_itemsets

    support                           itemsets  length
0  0.678229                     (has_comments)       1
1  0.889299                     (exec_inorder)       1
2  0.671587                (jupyter_prop_high)       1
3  0.676015                   (image_prop_low)       1
4  0.597048       (has_comments, exec_inorder)       2
5  0.602214  (exec_inorder, jupyter_prop_high)       2
6  0.611070     (image_prop_low, exec_inorder)       2

In [167]:
# filter down to itemsets that have at least 2 items
no_md_itemsets[no_md_itemsets['length'] >= 2]

    support                           itemsets  length
4  0.597048       (has_comments, exec_inorder)       2
5  0.602214  (exec_inorder, jupyter_prop_high)       2
6  0.611070     (image_prop_low, exec_inorder)       2

## Extracting Association Rules

### Markdown Cells

In [168]:
# use the itemsets to extract association rules
md_association_rules = association_rules(md_itemsets, metric = 'confidence', min_threshold = 0.7)
md_association_rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(longer_beginning),(has_comments),0.543867,0.889568,0.503274,0.925361,1.040237,0.019467,1.479553
1,(longer_beginning),(exec_inorder),0.543867,0.951550,0.516368,0.949438,0.997781,-0.001148,0.958242
2,(is_education),(has_comments),0.576604,0.889568,0.516805,0.896291,1.007557,0.003876,1.064824
3,(is_education),(exec_inorder),0.576604,0.951550,0.548669,0.951552,1.000002,0.000001,1.000048
4,(has_title),(has_comments),0.645133,0.889568,0.574422,0.890392,1.000927,0.000532,1.007523
...,...,...,...,...,...,...,...,...,...
143,"(markdown_prop_medium, exec_inorder)","(non_exec_prop_low, jupyter_prop_high)",0.780882,0.686163,0.552597,0.707658,1.031326,0.016785,1.073526
144,"(markdown_prop_medium, non_exec_prop_low)","(exec_inorder, jupyter_prop_high)",0.720210,0.750764,0.552597,0.767273,1.021989,0.011890,1.070937
145,"(exec_inorder, jupyter_prop_high)","(markdown_prop_medium, non_exec_prop_low)",0.750764,0.720210,0.552597,0.736047,1.021989,0.011890,1.059999
146,"(non_exec_prop_low, jupyter_prop_high)","(markdown_prop_medium, exec_inorder)",0.686163,0.780882,0.552597,0.805344,1.031326,0.016785,1.125667
147,(jupyter_prop_high),"(markdown_prop_medium, exec_inorder, non_exec_...",0.787429,0.683544,0.552597,0.701774,1.026669,0.014354,1.061127

In [169]:
# add columns that hold length
md_association_rules['antecedent_len'] = md_association_rules['antecedents'].apply(len)
md_association_rules['consequent_len'] = md_association_rules['consequents'].apply(len)

In [170]:
# filter down to rules that have 1 antecedent and 1 consequent
md_association_rules[(md_association_rules['antecedent_len'] == 1) &
                    (md_association_rules['consequent_len'] == 1) &
                    (md_association_rules['confidence'] >= 0.8)]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedent_len,consequent_len
0,(longer_beginning),(has_comments),0.543867,0.889568,0.503274,0.925361,1.040237,0.019467,1.479553,1,1
1,(longer_beginning),(exec_inorder),0.543867,0.951550,0.516368,0.949438,0.997781,-0.001148,0.958242,1,1
2,(is_education),(has_comments),0.576604,0.889568,0.516805,0.896291,1.007557,0.003876,1.064824,1,1
3,(is_education),(exec_inorder),0.576604,0.951550,0.548669,0.951552,1.000002,0.000001,1.000048,1,1
4,(has_title),(has_comments),0.645133,0.889568,0.574422,0.890392,1.000927,0.000532,1.007523,1,1
5,(has_comments),(exec_inorder),0.889568,0.951550,0.848101,0.953386,1.001930,0.001633,1.039390,1,1
6,(exec_inorder),(has_comments),0.951550,0.889568,0.848101,0.891284,1.001930,0.001633,1.015789,1,1
8,(jupyter_prop_high),(has_comments),0.787429,0.889568,0.700131,0.889135,0.999514,-0.000341,0.996098,1,1
9,(markdown_prop_medium),(has_comments),0.820166,0.889568,0.736796,0.898350,1.009873,0.007203,1.086398,1,1
10,(has_comments),(markdown_prop_medium),0.889568,0.820166,0.736796,0.828263,1.009873,0.007203,1.047148,1,1
11,(has_comments),(non_exec_prop_low),0.889568,0.874291,0.774771,0.870952,0.996181,-0.002970,0.974128,1,1
12,(non_exec_prop_low),(has_comments),0.874291,0.889568,0.774771,0.886171,0.996181,-0.002970,0.970156,1,1
13,(has_title),(exec_inorder),0.645133,0.951550,0.621126,0.962788,1.011810,0.007250,1.301996,1,1
15,(has_title),(markdown_prop_medium),0.645133,0.820166,0.530336,0.822057,1.002306,0.001220,1.010627,1,1
16,(has_title),(non_exec_prop_low),0.645133,0.874291,0.566565,0.878214,1.004487,0.002531,1.032213,1,1
18,(jupyter_prop_high),(exec_inorder),0.787429,0.951550,0.750764,0.953437,1.001983,0.001486,1.040531,1,1
19,(markdown_prop_medium),(exec_inorder),0.820166,0.951550,0.780882,0.952102,1.000581,0.000453,1.011538,1,1
20,(exec_inorder),(markdown_prop_medium),0.951550,0.820166,0.780882,0.820642,1.000581,0.000453,1.002656,1,1
21,(image_prop_low),(exec_inorder),0.541685,0.951550,0.520297,0.960516,1.009423,0.004857,1.227082,1,1
22,(md_frequency_medium),(exec_inorder),0.556962,0.951550,0.528154,0.948276,0.996560,-0.001823,0.936709,1,1
23,(exec_inorder),(non_exec_prop_low),0.951550,0.874291,0.829769,0.872018,0.997401,-0.002162,0.982245,1,1
24,(non_exec_prop_low),(exec_inorder),0.874291,0.951550,0.829769,0.949076,0.997401,-0.002162,0.951434,1,1
25,(markdown_prop_medium),(jupyter_prop_high),0.820166,0.787429,0.664339,0.810005,1.028671,0.018516,1.118826,1,1
26,(jupyter_prop_high),(markdown_prop_medium),0.787429,0.820166,0.664339,0.843681,1.028671,0.018516,1.150428,1,1
27,(jupyter_prop_high),(non_exec_prop_low),0.787429,0.874291,0.686163,0.871397,0.996690,-0.002279,0.977498,1,1
29,(markdown_prop_medium),(non_exec_prop_low),0.820166,0.874291,0.720210,0.878127,1.004388,0.003146,1.031475,1,1
30,(non_exec_prop_low),(markdown_prop_medium),0.874291,0.820166,0.720210,0.823764,1.004388,0.003146,1.020419,1,1

### No Markdown Cells

In [171]:
# use the itemsets to extract association rules
no_md_association_rules = association_rules(no_md_itemsets, metric = 'confidence', min_threshold = 0.5)
no_md_association_rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(has_comments),(exec_inorder),0.678229,0.889299,0.597048,0.880305,0.989886,-0.006100,0.924857
1,(exec_inorder),(has_comments),0.889299,0.678229,0.597048,0.671369,0.989886,-0.006100,0.979127
2,(exec_inorder),(jupyter_prop_high),0.889299,0.671587,0.602214,0.677178,1.008326,0.004973,1.017321
3,(jupyter_prop_high),(exec_inorder),0.671587,0.889299,0.602214,0.896703,1.008326,0.004973,1.071681
4,(image_prop_low),(exec_inorder),0.676015,0.889299,0.611070,0.903930,1.016453,0.009891,1.152298
5,(exec_inorder),(image_prop_low),0.889299,0.676015,0.611070,0.687137,1.016453,0.009891,1.035550

# Association Rule Mining (with all dummies)

## One Hot Encoding

We create dummy variables for every single variable, instead of those with low/medium/high

### Markdown Cells

In [172]:
# create a copy of the dataframe we will one-hot encode
md_one_hot = md_original.copy()

In [173]:
# drop the first two columns 
md_one_hot = md_one_hot.drop(['Unnamed: 0', 'nb_id'], axis = 1)

In [174]:
# initial look at the data
md_one_hot.head()

,longer_beginning,longer_ending,has_author,has_equation,jupyter_prop,markdown_prop,num_contrib,image_prop,is_education,has_links,has_comments,md_frequency,has_title,num_commits,md_format,non_exec_prop,exec_inorder,exec_skips,has_error
0,True,False,False,False,medium,low,lower,low,True,True,False,low,True,lower,True,low,higher,lower,False
1,True,False,False,False,high,medium,lower,low,True,True,True,medium,False,lower,True,high,higher,lower,False
2,True,False,False,False,high,medium,lower,low,True,True,True,medium,True,lower,True,high,higher,lower,False
3,True,False,False,False,high,medium,lower,low,True,True,True,medium,True,lower,False,low,higher,lower,False
4,True,False,False,True,high,medium,lower,low,False,False,True,medium,False,lower,False,low,higher,lower,False

In [175]:
# change True/False to T/F for simplicity
md_one_hot = md_one_hot.replace(True, 'T')
md_one_hot = md_one_hot.replace(False, 'F')

In [176]:
# change medium to med for simplicity
md_one_hot = md_one_hot.replace('medium', 'med')

In [177]:
# check the data again
md_one_hot.head()

,longer_beginning,longer_ending,has_author,has_equation,jupyter_prop,markdown_prop,num_contrib,image_prop,is_education,has_links,has_comments,md_frequency,has_title,num_commits,md_format,non_exec_prop,exec_inorder,exec_skips,has_error
0,T,F,F,F,med,low,lower,low,T,T,F,low,T,lower,T,low,higher,lower,F
1,T,F,F,F,high,med,lower,low,T,T,T,med,F,lower,T,high,higher,lower,F
2,T,F,F,F,high,med,lower,low,T,T,T,med,T,lower,T,high,higher,lower,F
3,T,F,F,F,high,med,lower,low,T,T,T,med,T,lower,F,low,higher,lower,F
4,T,F,F,T,high,med,lower,low,F,F,T,med,F,lower,F,low,higher,lower,F

In [178]:
# create dummy variables for all variables
md_one_hot = pd.get_dummies(md_one_hot)

In [179]:
# look at the one-hot encoded data
md_one_hot.head()

,longer_beginning_F,longer_beginning_T,longer_ending_F,longer_ending_T,has_author_F,has_author_T,has_equation_F,has_equation_T,jupyter_prop_high,jupyter_prop_low,...,md_format_T,non_exec_prop_high,non_exec_prop_low,non_exec_prop_med,exec_inorder_higher,exec_inorder_lower,exec_skips_higher,exec_skips_lower,has_error_F,has_error_T
0,0,1,1,0,1,0,1,0,0,0,...,1,0,1,0,1,0,0,1,1,0
1,0,1,1,0,1,0,1,0,1,0,...,1,1,0,0,1,0,0,1,1,0
2,0,1,1,0,1,0,1,0,1,0,...,1,1,0,0,1,0,0,1,1,0
3,0,1,1,0,1,0,1,0,1,0,...,0,0,1,0,1,0,0,1,1,0
4,0,1,1,0,1,0,0,1,1,0,...,0,0,1,0,1,0,0,1,1,0

In [180]:
# check the fields
md_one_hot.columns

Index(['longer_beginning_F', 'longer_beginning_T', 'longer_ending_F',
       'longer_ending_T', 'has_author_F', 'has_author_T', 'has_equation_F',
       'has_equation_T', 'jupyter_prop_high', 'jupyter_prop_low',
       'jupyter_prop_med', 'markdown_prop_high', 'markdown_prop_low',
       'markdown_prop_med', 'num_contrib_higher', 'num_contrib_lower',
       'image_prop_high', 'image_prop_low', 'image_prop_med', 'is_education_F',
       'is_education_T', 'has_links_F', 'has_links_T', 'has_comments_F',
       'has_comments_T', 'md_frequency_high', 'md_frequency_low',
       'md_frequency_med', 'has_title_F', 'has_title_T', 'num_commits_higher',
       'num_commits_lower', 'md_format_F', 'md_format_T', 'non_exec_prop_high',
       'non_exec_prop_low', 'non_exec_prop_med', 'exec_inorder_higher',
       'exec_inorder_lower', 'exec_skips_higher', 'exec_skips_lower',
       'has_error_F', 'has_error_T'],
      dtype='object')

### No Markdown Cells

In [181]:
# create a copy of the dataframe we will one-hot encode
no_md_one_hot = no_md_original.copy()

In [182]:
# drop the first two columns
no_md_one_hot = no_md_one_hot.drop(['Unnamed: 0', 'nb_id'], axis = 1)

In [183]:
# initial look at the data
no_md_one_hot.head()

,has_author,jupyter_prop,num_contrib,image_prop,is_education,has_comments,num_commits,non_exec_prop,exec_inorder,exec_skips,has_error
0,False,medium,lower,low,False,False,lower,lower,higher,lower,False
1,False,high,lower,low,False,True,lower,lower,higher,lower,True
2,False,low,higher,low,False,True,higher,lower,higher,lower,False
3,False,high,lower,low,False,True,lower,lower,higher,lower,False
4,False,high,lower,low,False,True,higher,lower,higher,lower,True

In [184]:
# change True/False to T/F 
no_md_one_hot = no_md_one_hot.replace(True, 'T')
no_md_one_hot = no_md_one_hot.replace(False, 'F')

# change medium to med
no_md_one_hot = no_md_one_hot.replace('medium', 'med')

In [185]:
# check the data again
no_md_one_hot.head()

,has_author,jupyter_prop,num_contrib,image_prop,is_education,has_comments,num_commits,non_exec_prop,exec_inorder,exec_skips,has_error
0,F,med,lower,low,F,F,lower,lower,higher,lower,F
1,F,high,lower,low,F,T,lower,lower,higher,lower,T
2,F,low,higher,low,F,T,higher,lower,higher,lower,F
3,F,high,lower,low,F,T,lower,lower,higher,lower,F
4,F,high,lower,low,F,T,higher,lower,higher,lower,T

In [186]:
# create all dummy variables
no_md_one_hot = pd.get_dummies(no_md_one_hot)

In [187]:
# look at the one-hot encoded data
no_md_one_hot.head()

,has_author_F,has_author_T,jupyter_prop_high,jupyter_prop_low,jupyter_prop_med,num_contrib_higher,num_contrib_lower,image_prop_high,image_prop_low,image_prop_med,...,num_commits_higher,num_commits_lower,non_exec_prop_higher,non_exec_prop_lower,exec_inorder_higher,exec_inorder_lower,exec_skips_higher,exec_skips_lower,has_error_F,has_error_T
0,1,0,0,0,1,0,1,0,1,0,...,0,1,0,1,1,0,0,1,1,0
1,1,0,1,0,0,0,1,0,1,0,...,0,1,0,1,1,0,0,1,0,1
2,1,0,0,1,0,1,0,0,1,0,...,1,0,0,1,1,0,0,1,1,0
3,1,0,1,0,0,0,1,0,1,0,...,0,1,0,1,1,0,0,1,1,0
4,1,0,1,0,0,0,1,0,1,0,...,1,0,0,1,1,0,0,1,0,1

In [188]:
# check the fields
no_md_one_hot.columns

Index(['has_author_F', 'has_author_T', 'jupyter_prop_high', 'jupyter_prop_low',
       'jupyter_prop_med', 'num_contrib_higher', 'num_contrib_lower',
       'image_prop_high', 'image_prop_low', 'image_prop_med', 'is_education_F',
       'is_education_T', 'has_comments_F', 'has_comments_T',
       'num_commits_higher', 'num_commits_lower', 'non_exec_prop_higher',
       'non_exec_prop_lower', 'exec_inorder_higher', 'exec_inorder_lower',
       'exec_skips_higher', 'exec_skips_lower', 'has_error_F', 'has_error_T'],
      dtype='object')

## Performing the Apriori Algorithm

### Markdown Cells

In [189]:
# requires True/False instead of 1/0
md_one_hot = md_one_hot.replace(1, True)
md_one_hot = md_one_hot.replace(0, False)

In [190]:
# initial look at the data
md_one_hot.head()

,longer_beginning_F,longer_beginning_T,longer_ending_F,longer_ending_T,has_author_F,has_author_T,has_equation_F,has_equation_T,jupyter_prop_high,jupyter_prop_low,...,md_format_T,non_exec_prop_high,non_exec_prop_low,non_exec_prop_med,exec_inorder_higher,exec_inorder_lower,exec_skips_higher,exec_skips_lower,has_error_F,has_error_T
0,False,True,True,False,True,False,True,False,False,False,...,True,False,True,False,True,False,False,True,True,False
1,False,True,True,False,True,False,True,False,True,False,...,True,True,False,False,True,False,False,True,True,False
2,False,True,True,False,True,False,True,False,True,False,...,True,True,False,False,True,False,False,True,True,False
3,False,True,True,False,True,False,True,False,True,False,...,False,False,True,False,True,False,False,True,True,False
4,False,True,True,False,True,False,False,True,True,False,...,False,False,True,False,True,False,False,True,True,False

In [191]:
# perform apriori algorithm on the dataframe
md_itemsets = apriori(md_one_hot, min_support = 0.5, use_colnames = True)

# look at the itemsets
md_itemsets

       support                                           itemsets
0     0.543867                               (longer_beginning_T)
1     0.741161                                  (longer_ending_F)
2     0.953296                                     (has_author_F)
3     0.806198                                   (has_equation_F)
4     0.787429                                (jupyter_prop_high)
...        ...                                                ...
1262  0.522916  (exec_inorder_higher, has_error_F, non_exec_pr...
1263  0.502837  (exec_inorder_higher, has_author_F, non_exec_p...
1264  0.512003  (exec_inorder_higher, has_error_F, has_author_...
1265  0.504583  (exec_inorder_higher, has_error_F, has_author_...
1266  0.505020  (exec_inorder_higher, has_error_F, has_author_...

[1267 rows x 2 columns]

In [192]:
# add a column that counts the number of elements in the itemset
md_itemsets['length'] = md_itemsets['itemsets'].apply(len)
md_itemsets

       support                                           itemsets  length
0     0.543867                               (longer_beginning_T)       1
1     0.741161                                  (longer_ending_F)       1
2     0.953296                                     (has_author_F)       1
3     0.806198                                   (has_equation_F)       1
4     0.787429                                (jupyter_prop_high)       1
...        ...                                                ...     ...
1262  0.522916  (exec_inorder_higher, has_error_F, non_exec_pr...       6
1263  0.502837  (exec_inorder_higher, has_author_F, non_exec_p...       7
1264  0.512003  (exec_inorder_higher, has_error_F, has_author_...       7
1265  0.504583  (exec_inorder_higher, has_error_F, has_author_...       7
1266  0.505020  (exec_inorder_higher, has_error_F, has_author_...       7

[1267 rows x 3 columns]

In [193]:
# filter the itemsets
md_itemsets[(md_itemsets['length'] >= 2) &
           (md_itemsets['support'] >= 0.8)]

      support                                           itemsets  length
38   0.888695                  (num_contrib_lower, has_author_F)       2
42   0.846355                     (has_comments_T, has_author_F)       2
45   0.831951                  (num_commits_lower, has_author_F)       2
47   0.833697                  (has_author_F, non_exec_prop_low)       2
48   0.907900                (exec_inorder_higher, has_author_F)       2
49   0.806635                   (has_author_F, exec_skips_lower)       2
50   0.824094                        (has_error_F, has_author_F)       2
83   0.835443                (num_contrib_lower, has_comments_T)       2
86   0.828023             (num_contrib_lower, num_commits_lower)       2
88   0.826713             (num_contrib_lower, non_exec_prop_low)       2
89   0.888258           (exec_inorder_higher, num_contrib_lower)       2
91   0.806635                   (num_contrib_lower, has_error_F)       2
105  0.848101              (exec_inorder_higher, has_comments_T)       2
115  0.824967           (exec_inorder_higher, num_commits_lower)       2
119  0.829769           (exec_inorder_higher, non_exec_prop_low)       2
122  0.820166            (exec_inorder_higher, exec_skips_lower)       2
123  0.828459                 (exec_inorder_higher, has_error_F)       2
216  0.845482  (exec_inorder_higher, num_contrib_lower, has_a...       3
229  0.807944  (exec_inorder_higher, has_comments_T, has_auth...       3

### No Markdown Cells

In [194]:
# replace 1/0 with True/False
no_md_one_hot = no_md_one_hot.replace(1, True)
no_md_one_hot = no_md_one_hot.replace(0, False)

In [195]:
# initial look at the data
no_md_one_hot.head()

,has_author_F,has_author_T,jupyter_prop_high,jupyter_prop_low,jupyter_prop_med,num_contrib_higher,num_contrib_lower,image_prop_high,image_prop_low,image_prop_med,...,num_commits_higher,num_commits_lower,non_exec_prop_higher,non_exec_prop_lower,exec_inorder_higher,exec_inorder_lower,exec_skips_higher,exec_skips_lower,has_error_F,has_error_T
0,True,False,False,False,True,False,True,False,True,False,...,False,True,False,True,True,False,False,True,True,False
1,True,False,True,False,False,False,True,False,True,False,...,False,True,False,True,True,False,False,True,False,True
2,True,False,False,True,False,True,False,False,True,False,...,True,False,False,True,True,False,False,True,True,False
3,True,False,True,False,False,False,True,False,True,False,...,False,True,False,True,True,False,False,True,True,False
4,True,False,True,False,False,False,True,False,True,False,...,True,False,False,True,True,False,False,True,False,True

In [196]:
# perform apriori algorithm on the dataframe
no_md_itemsets = apriori(no_md_one_hot, min_support = 0.5, use_colnames = True)

# look at the itemsets
no_md_itemsets

      support                                           itemsets
0    0.991144                                     (has_author_F)
1    0.671587                                (jupyter_prop_high)
2    0.912915                                (num_contrib_lower)
3    0.676015                                   (image_prop_low)
4    0.892251                                   (is_education_F)
..        ...                                                ...
341  0.540221  (exec_inorder_higher, has_error_F, has_author_...
342  0.514391  (exec_inorder_higher, non_exec_prop_lower, has...
343  0.549815  (exec_inorder_higher, non_exec_prop_lower, has...
344  0.502583  (exec_inorder_higher, non_exec_prop_lower, has...
345  0.551292  (exec_inorder_higher, non_exec_prop_lower, has...

[346 rows x 2 columns]

In [197]:
# add a column that counts the number of elements in the itemset
no_md_itemsets['length'] = no_md_itemsets['itemsets'].apply(len)
no_md_itemsets

      support                                           itemsets  length
0    0.991144                                     (has_author_F)       1
1    0.671587                                (jupyter_prop_high)       1
2    0.912915                                (num_contrib_lower)       1
3    0.676015                                   (image_prop_low)       1
4    0.892251                                   (is_education_F)       1
..        ...                                                ...     ...
341  0.540221  (exec_inorder_higher, has_error_F, has_author_...       6
342  0.514391  (exec_inorder_higher, non_exec_prop_lower, has...       6
343  0.549815  (exec_inorder_higher, non_exec_prop_lower, has...       6
344  0.502583  (exec_inorder_higher, non_exec_prop_lower, has...       6
345  0.551292  (exec_inorder_higher, non_exec_prop_lower, has...       6

[346 rows x 3 columns]

In [198]:
# filter down to itemsets that have at least 2 items and 0.7 support
no_md_itemsets[(no_md_itemsets['length'] >= 2) &
              (no_md_itemsets['support'] >= 0.8)]

     support                                           itemsets  length
12  0.904797                  (num_contrib_lower, has_author_F)       2
14  0.883395                     (has_author_F, is_education_F)       2
17  0.916605                (non_exec_prop_lower, has_author_F)       2
18  0.881181                (exec_inorder_higher, has_author_F)       2
19  0.861993                   (has_author_F, exec_skips_lower)       2
20  0.833948                        (has_error_F, has_author_F)       2
29  0.810332                (num_contrib_lower, is_education_F)       2
32  0.839852           (non_exec_prop_lower, num_contrib_lower)       2
33  0.806642           (exec_inorder_higher, num_contrib_lower)       2
44  0.825092              (non_exec_prop_lower, is_education_F)       2
56  0.813284         (exec_inorder_higher, non_exec_prop_lower)       2
70  0.802214  (num_contrib_lower, has_author_F, is_education_F)       3
73  0.835424  (non_exec_prop_lower, num_contrib_lower, has_a...       3
85  0.819926  (non_exec_prop_lower, has_author_F, is_educati...       3
97  0.808856  (exec_inorder_higher, non_exec_prop_lower, has...       3

## Extracting Association Rules

### Markdown Cells

In [199]:
# use the itemsets to extract association rules
md_association_rules = association_rules(md_itemsets, metric = 'confidence', min_threshold = 0.7)
md_association_rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(longer_beginning_T),(has_author_F),0.543867,0.953296,0.515932,0.948636,0.995112,-0.002534,0.909278
1,(longer_beginning_T),(num_contrib_lower),0.543867,0.934090,0.503710,0.926164,0.991515,-0.004311,0.892652
2,(longer_beginning_T),(has_comments_T),0.543867,0.889568,0.503274,0.925361,1.040237,0.019467,1.479553
3,(longer_beginning_T),(exec_inorder_higher),0.543867,0.951550,0.516368,0.949438,0.997781,-0.001148,0.958242
4,(longer_ending_F),(has_author_F),0.741161,0.953296,0.713226,0.962309,1.009455,0.006680,1.239129
...,...,...,...,...,...,...,...,...,...
16620,"(num_commits_lower, has_author_F, exec_skips_l...","(exec_inorder_higher, num_contrib_lower, has_e...",0.710607,0.683544,0.505020,0.710688,1.039710,0.019288,1.093821
16621,"(num_contrib_lower, exec_skips_lower, non_exec...","(exec_inorder_higher, num_commits_lower, has_e...",0.677433,0.690965,0.505020,0.745490,1.078911,0.036937,1.214235
16622,"(exec_skips_lower, num_commits_lower, non_exec...","(exec_inorder_higher, num_contrib_lower, has_e...",0.633348,0.732868,0.505020,0.797381,1.088029,0.040859,1.318398
16623,"(num_contrib_lower, num_commits_lower, exec_sk...","(exec_inorder_higher, has_error_F, has_author_...",0.698821,0.687909,0.505020,0.722673,1.050536,0.024294,1.125354
16624,"(exec_skips_lower, non_exec_prop_low)","(exec_inorder_higher, has_error_F, has_author_...",0.721082,0.660847,0.505020,0.700363,1.059797,0.028495,1.131881

In [200]:
# add columns that hold length
md_association_rules['antecedent_len'] = md_association_rules['antecedents'].apply(len)
md_association_rules['consequent_len'] = md_association_rules['consequents'].apply(len)

In [201]:
# filter the rules
md_association_rules[(md_association_rules['antecedent_len'] == 1) &
                    (md_association_rules['consequent_len'] == 1) &
                    (md_association_rules['confidence'] >= 0.95)]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedent_len,consequent_len
4,(longer_ending_F),(has_author_F),0.741161,0.953296,0.713226,0.962309,1.009455,0.006680,1.239129,1,1
28,(has_equation_F),(has_author_F),0.806198,0.953296,0.773461,0.959394,1.006397,0.004916,1.150176,1,1
31,(jupyter_prop_high),(has_author_F),0.787429,0.953296,0.756438,0.960643,1.007707,0.005786,1.186689,1,1
32,(markdown_prop_med),(has_author_F),0.820166,0.953296,0.785247,0.957424,1.004331,0.003386,1.096972,1,1
34,(num_contrib_lower),(has_author_F),0.934090,0.953296,0.888695,0.951402,0.998014,-0.001769,0.961035,1,1
36,(image_prop_low),(has_author_F),0.541685,0.953296,0.516805,0.954069,1.000812,0.000419,1.016847,1,1
38,(has_links_F),(has_author_F),0.621126,0.953296,0.604540,0.973296,1.020980,0.012423,1.748960,1,1
39,(has_comments_T),(has_author_F),0.889568,0.953296,0.846355,0.951423,0.998036,-0.001666,0.961452,1,1
43,(num_commits_lower),(has_author_F),0.864688,0.953296,0.831951,0.962140,1.009278,0.007648,1.233621,1,1
45,(md_format_F),(has_author_F),0.539502,0.953296,0.525098,0.973301,1.020986,0.010793,1.749296,1,1
47,(non_exec_prop_low),(has_author_F),0.874291,0.953296,0.833697,0.953570,1.000288,0.000240,1.005904,1,1
48,(exec_inorder_higher),(has_author_F),0.951550,0.953296,0.907900,0.954128,1.000874,0.000793,1.018158,1,1
49,(has_author_F),(exec_inorder_higher),0.953296,0.951550,0.907900,0.952381,1.000874,0.000793,1.017460,1,1
51,(exec_skips_lower),(has_author_F),0.840244,0.953296,0.806635,0.960000,1.007033,0.005633,1.167612,1,1
52,(has_error_F),(has_author_F),0.865997,0.953296,0.824094,0.951613,0.998235,-0.001457,0.965226,1,1
69,(has_equation_F),(exec_inorder_higher),0.806198,0.951550,0.766041,0.950189,0.998571,-0.001096,0.972696,1,1
77,(jupyter_prop_high),(num_contrib_lower),0.787429,0.934090,0.752946,0.956208,1.023679,0.017417,1.505086,1,1
87,(jupyter_prop_high),(exec_inorder_higher),0.787429,0.951550,0.750764,0.953437,1.001983,0.001486,1.040531,1,1
103,(markdown_prop_med),(exec_inorder_higher),0.820166,0.951550,0.780882,0.952102,1.000581,0.000453,1.011538,1,1
115,(num_commits_lower),(num_contrib_lower),0.864688,0.934090,0.828023,0.957597,1.025166,0.020326,1.554379,1,1
120,(num_contrib_lower),(exec_inorder_higher),0.934090,0.951550,0.888258,0.950935,0.999354,-0.000574,0.987466,1,1
125,(image_prop_low),(exec_inorder_higher),0.541685,0.951550,0.520297,0.960516,1.009423,0.004857,1.227082,1,1
127,(is_education_T),(exec_inorder_higher),0.576604,0.951550,0.548669,0.951552,1.000002,0.000001,1.000048,1,1
132,(has_links_F),(exec_inorder_higher),0.621126,0.951550,0.593627,0.955727,1.004391,0.002595,1.094365,1,1
141,(has_comments_T),(exec_inorder_higher),0.889568,0.951550,0.848101,0.953386,1.001930,0.001633,1.039390,1,1
149,(has_title_T),(exec_inorder_higher),0.645133,0.951550,0.621126,0.962788,1.011810,0.007250,1.301996,1,1
155,(num_commits_lower),(exec_inorder_higher),0.864688,0.951550,0.824967,0.954064,1.002642,0.002174,1.054729,1,1
160,(md_format_F),(exec_inorder_higher),0.539502,0.951550,0.514186,0.953074,1.001603,0.000823,1.032496,1,1
168,(exec_skips_lower),(exec_inorder_higher),0.840244,0.951550,0.820166,0.976104,1.025805,0.020632,2.027546,1,1
170,(has_error_F),(exec_inorder_higher),0.865997,0.951550,0.828459,0.956653,1.005364,0.004420,1.117741,1,1

### No Markdown Cells

In [202]:
# use itemsets to extract association rules
no_md_association_rules = association_rules(no_md_itemsets, metric = 'confidence', min_threshold = 0.7)
no_md_association_rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(jupyter_prop_high),(has_author_F),0.671587,0.991144,0.669373,0.996703,1.005609,0.003734,2.686347
1,(num_contrib_lower),(has_author_F),0.912915,0.991144,0.904797,0.991108,0.999963,-0.000033,0.995907
2,(has_author_F),(num_contrib_lower),0.991144,0.912915,0.904797,0.912882,0.999963,-0.000033,0.999615
3,(image_prop_low),(has_author_F),0.676015,0.991144,0.667897,0.987991,0.996819,-0.002131,0.737471
4,(has_author_F),(is_education_F),0.991144,0.892251,0.883395,0.891288,0.998921,-0.000954,0.991144
...,...,...,...,...,...,...,...,...,...
2963,"(exec_inorder_higher, has_error_F)","(non_exec_prop_lower, exec_skips_lower, has_au...",0.766052,0.701107,0.551292,0.719653,1.026453,0.014207,1.066154
2964,"(non_exec_prop_lower, has_error_F)","(exec_inorder_higher, exec_skips_lower, has_au...",0.764576,0.702583,0.551292,0.721042,1.026274,0.014114,1.066173
2965,"(has_error_F, is_education_F)","(exec_inorder_higher, non_exec_prop_lower, has...",0.744649,0.718819,0.551292,0.740337,1.029935,0.016023,1.082868
2966,"(has_error_F, exec_skips_lower)","(exec_inorder_higher, non_exec_prop_lower, has...",0.751292,0.720295,0.551292,0.733792,1.018738,0.010140,1.050699
2967,"(exec_skips_lower, is_education_F)","(exec_inorder_higher, non_exec_prop_lower, has...",0.772694,0.687823,0.551292,0.713467,1.037283,0.019815,1.089498

In [203]:
# add columns that hold length
no_md_association_rules['antecedent_len'] = no_md_association_rules['antecedents'].apply(len)
no_md_association_rules['consequent_len'] = no_md_association_rules['consequents'].apply(len)

In [204]:
# filter the rules
no_md_association_rules[(no_md_association_rules['antecedent_len'] == 1) &
                       (no_md_association_rules['consequent_len'] == 1) &
                       (no_md_association_rules['confidence'] >= 0.9)]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedent_len,consequent_len
0,(jupyter_prop_high),(has_author_F),0.671587,0.991144,0.669373,0.996703,1.005609,0.003734,2.686347,1,1
1,(num_contrib_lower),(has_author_F),0.912915,0.991144,0.904797,0.991108,0.999963,-0.000033,0.995907,1,1
2,(has_author_F),(num_contrib_lower),0.991144,0.912915,0.904797,0.912882,0.999963,-0.000033,0.999615,1,1
3,(image_prop_low),(has_author_F),0.676015,0.991144,0.667897,0.987991,0.996819,-0.002131,0.737471,1,1
5,(is_education_F),(has_author_F),0.892251,0.991144,0.883395,0.990074,0.998921,-0.000954,0.892251,1,1
6,(has_comments_T),(has_author_F),0.678229,0.991144,0.669373,0.986942,0.995761,-0.002850,0.678229,1,1
7,(num_commits_lower),(has_author_F),0.769004,0.991144,0.761624,0.990403,0.999253,-0.000570,0.922804,1,1
9,(non_exec_prop_lower),(has_author_F),0.921771,0.991144,0.916605,0.994396,1.003281,0.002997,1.580179,1,1
10,(has_author_F),(non_exec_prop_lower),0.991144,0.921771,0.916605,0.924795,1.003281,0.002997,1.040210,1,1
11,(exec_inorder_higher),(has_author_F),0.889299,0.991144,0.881181,0.990871,0.999725,-0.000242,0.970144,1,1
14,(exec_skips_lower),(has_author_F),0.870111,0.991144,0.861993,0.990670,0.999522,-0.000412,0.949212,1,1
15,(has_error_F),(has_author_F),0.840590,0.991144,0.833948,0.992098,1.000963,0.000802,1.120787,1,1
17,(jupyter_prop_high),(num_contrib_lower),0.671587,0.912915,0.614760,0.915385,1.002705,0.001658,1.029185,1,1
18,(jupyter_prop_high),(is_education_F),0.671587,0.892251,0.610332,0.908791,1.018538,0.011108,1.181345,1,1
20,(jupyter_prop_high),(non_exec_prop_lower),0.671587,0.921771,0.622878,0.927473,1.006185,0.003829,1.078609,1,1
26,(is_education_F),(num_contrib_lower),0.892251,0.912915,0.810332,0.908189,0.994823,-0.004217,0.948519,1,1
27,(has_comments_T),(num_contrib_lower),0.678229,0.912915,0.619926,0.914037,1.001229,0.000761,1.013051,1,1
29,(num_commits_lower),(num_contrib_lower),0.769004,0.912915,0.711439,0.925144,1.013395,0.009404,1.163365,1,1
30,(non_exec_prop_lower),(num_contrib_lower),0.921771,0.912915,0.839852,0.911129,0.998043,-0.001646,0.979901,1,1
31,(num_contrib_lower),(non_exec_prop_lower),0.912915,0.921771,0.839852,0.919968,0.998043,-0.001646,0.977465,1,1
32,(exec_inorder_higher),(num_contrib_lower),0.889299,0.912915,0.806642,0.907054,0.993580,-0.005212,0.936940,1,1
35,(exec_skips_lower),(num_contrib_lower),0.870111,0.912915,0.786716,0.904156,0.990405,-0.007621,0.908611,1,1
37,(has_error_F),(num_contrib_lower),0.840590,0.912915,0.757934,0.901668,0.987680,-0.009454,0.885622,1,1
42,(image_prop_low),(exec_inorder_higher),0.676015,0.889299,0.611070,0.903930,1.016453,0.009891,1.152298,1,1
49,(is_education_F),(non_exec_prop_lower),0.892251,0.921771,0.825092,0.924731,1.003211,0.002641,1.039325,1,1
56,(has_comments_T),(non_exec_prop_lower),0.678229,0.921771,0.616974,0.909684,0.986887,-0.008198,0.866172,1,1
61,(num_commits_lower),(non_exec_prop_lower),0.769004,0.921771,0.710701,0.924184,1.002618,0.001856,1.031828,1,1
68,(exec_inorder_higher),(non_exec_prop_lower),0.889299,0.921771,0.813284,0.914523,0.992136,-0.006446,0.915201,1,1
71,(exec_skips_lower),(non_exec_prop_lower),0.870111,0.921771,0.791882,0.910093,0.987331,-0.010161,0.870111,1,1
73,(has_error_F),(non_exec_prop_lower),0.840590,0.921771,0.764576,0.909570,0.986763,-0.010256,0.865074,1,1
75,(exec_skips_lower),(exec_inorder_higher),0.870111,0.889299,0.799262,0.918575,1.032921,0.025474,1.359548,1,1
77,(has_error_F),(exec_inorder_higher),0.840590,0.889299,0.766052,0.911326,1.024769,0.018516,1.248402,1,1

# Export Itemsets and Rules

## Markdown Cells

In [205]:
# check the data
md_itemsets.head()

    support              itemsets  length
0  0.543867  (longer_beginning_T)       1
1  0.741161     (longer_ending_F)       1
2  0.953296        (has_author_F)       1
3  0.806198      (has_equation_F)       1
4  0.787429   (jupyter_prop_high)       1

In [206]:
# extract itemsets to a pickle
md_itemsets.to_pickle('rule-mining/md_frequent_itemsets.pkl')

In [207]:
# check the data
md_association_rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedent_len,consequent_len
0,(longer_beginning_T),(has_author_F),0.543867,0.953296,0.515932,0.948636,0.995112,-0.002534,0.909278,1,1
1,(longer_beginning_T),(num_contrib_lower),0.543867,0.934090,0.503710,0.926164,0.991515,-0.004311,0.892652,1,1
2,(longer_beginning_T),(has_comments_T),0.543867,0.889568,0.503274,0.925361,1.040237,0.019467,1.479553,1,1
3,(longer_beginning_T),(exec_inorder_higher),0.543867,0.951550,0.516368,0.949438,0.997781,-0.001148,0.958242,1,1
4,(longer_ending_F),(has_author_F),0.741161,0.953296,0.713226,0.962309,1.009455,0.006680,1.239129,1,1

In [208]:
# extract rules to a pickle
md_association_rules.to_pickle('rule-mining/md_association_rules.pkl')

## No Markdown Cells

In [209]:
# check the data
no_md_itemsets.head()

    support             itemsets  length
0  0.991144       (has_author_F)       1
1  0.671587  (jupyter_prop_high)       1
2  0.912915  (num_contrib_lower)       1
3  0.676015     (image_prop_low)       1
4  0.892251     (is_education_F)       1

In [210]:
# extract itemsets to a pickle
no_md_itemsets.to_pickle('rule-mining/no_md_frequent_itemsets.pkl')

In [211]:
# check the data
no_md_association_rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedent_len,consequent_len
0,(jupyter_prop_high),(has_author_F),0.671587,0.991144,0.669373,0.996703,1.005609,0.003734,2.686347,1,1
1,(num_contrib_lower),(has_author_F),0.912915,0.991144,0.904797,0.991108,0.999963,-0.000033,0.995907,1,1
2,(has_author_F),(num_contrib_lower),0.991144,0.912915,0.904797,0.912882,0.999963,-0.000033,0.999615,1,1
3,(image_prop_low),(has_author_F),0.676015,0.991144,0.667897,0.987991,0.996819,-0.002131,0.737471,1,1
4,(has_author_F),(is_education_F),0.991144,0.892251,0.883395,0.891288,0.998921,-0.000954,0.991144,1,1

In [212]:
# extract rules to a pickle
no_md_association_rules.to_pickle('rule-mining/no_md_association_rules.pkl')