# Imports

In [1]:
import pandas as pd

# Loading the Data

In [5]:
md_original = pd.read_pickle('full_markdown_group.pkl')
no_md_original = pd.read_pickle('full_no_markdown_group.pkl')

In [6]:
# drop the first column in both
md_df = md_original.drop(['nb_id', 'repo_id'], axis = 1)
no_md_df = no_md_original.drop(['nb_id', 'repo_id'], axis = 1)

In [7]:
md_df.head()

,longer_beginning,longer_ending,has_author,has_equation,jupyter_prop,output_cell_prop,markdown_prop,num_contrib,image_prop,is_education,...,exec_inorder,exec_skips,has_error,has_export,num_functions,has_test,num_headers,has_param,has_reqtext,num_stars
79,True,True,False,False,0.930911,0.363636,0.775510,1.0,0.0,True,...,0.75,4.500000,False,False,2.0,False,27.0,False,False,1.0
80,True,True,False,False,0.930911,0.000000,0.775510,1.0,0.0,True,...,1.00,0.000000,False,False,2.0,False,27.0,False,False,1.0
81,False,False,False,False,1.000000,0.560000,0.390244,1.0,0.0,True,...,1.00,1.913043,False,False,6.0,False,13.0,False,False,1.0
82,False,False,False,False,1.000000,0.560000,0.390244,1.0,0.0,True,...,1.00,1.913043,False,False,6.0,False,13.0,False,False,1.0
83,False,False,False,False,1.000000,0.588235,0.346154,1.0,0.0,True,...,1.00,0.000000,False,False,8.0,False,13.0,False,False,1.0

In [8]:
no_md_df.head()

,has_author,jupyter_prop,output_cell_prop,num_contrib,image_prop,is_education,has_comments,num_commits,non_exec_prop,exec_inorder,exec_skips,has_error,has_export,num_functions,has_test,has_param,has_reqtext,num_stars
85,False,1.000000,0.500000,1.0,0.000000,False,True,1.0,0.500000,1.000000,0.000000,False,False,1.0,False,False,False,0.0
90,False,1.000000,0.571429,1.0,0.416667,False,True,1.0,0.047619,0.944444,4.555556,False,False,1.0,False,False,False,0.0
91,False,1.000000,0.595745,1.0,0.571429,False,True,1.0,0.000000,0.956522,3.543478,True,True,1.0,False,False,False,0.0
94,False,0.578178,0.000000,1.0,0.000000,False,True,1.0,0.976190,1.000000,0.000000,False,True,21.0,False,False,False,0.0
109,False,0.967215,0.727273,1.0,0.250000,False,False,1.0,0.000000,1.000000,1.400000,False,False,0.0,False,False,False,0.0

# Checking Datatypes

In [9]:
list(enumerate(zip(md_df.columns, md_df.dtypes)))

[(0, ('longer_beginning', dtype('O'))),
 (1, ('longer_ending', dtype('O'))),
 (2, ('has_author', dtype('O'))),
 (3, ('has_equation', dtype('O'))),
 (4, ('jupyter_prop', dtype('float64'))),
 (5, ('output_cell_prop', dtype('float64'))),
 (6, ('markdown_prop', dtype('float64'))),
 (7, ('num_contrib', dtype('float64'))),
 (8, ('image_prop', dtype('float64'))),
 (9, ('is_education', dtype('O'))),
 (10, ('has_links', dtype('O'))),
 (11, ('has_comments', dtype('O'))),
 (12, ('md_frequency', dtype('float64'))),
 (13, ('has_title', dtype('O'))),
 (14, ('num_commits', dtype('float64'))),
 (15, ('md_format', dtype('O'))),
 (16, ('non_exec_prop', dtype('float64'))),
 (17, ('exec_inorder', dtype('float64'))),
 (18, ('exec_skips', dtype('float64'))),
 (19, ('has_error', dtype('O'))),
 (20, ('has_export', dtype('O'))),
 (21, ('num_functions', dtype('float64'))),
 (22, ('has_test', dtype('O'))),
 (23, ('num_headers', dtype('float64'))),
 (24, ('has_param', dtype('O'))),
 (25, ('has_reqtext', dtype('O'))),
 (26, ('num_stars', dtype('float64')))]

In [10]:
list(enumerate(zip(no_md_df.columns, no_md_df.dtypes)))

[(0, ('has_author', dtype('O'))),
 (1, ('jupyter_prop', dtype('float64'))),
 (2, ('output_cell_prop', dtype('float64'))),
 (3, ('num_contrib', dtype('float64'))),
 (4, ('image_prop', dtype('float64'))),
 (5, ('is_education', dtype('O'))),
 (6, ('has_comments', dtype('O'))),
 (7, ('num_commits', dtype('float64'))),
 (8, ('non_exec_prop', dtype('float64'))),
 (9, ('exec_inorder', dtype('float64'))),
 (10, ('exec_skips', dtype('float64'))),
 (11, ('has_error', dtype('O'))),
 (12, ('has_export', dtype('O'))),
 (13, ('num_functions', dtype('float64'))),
 (14, ('has_test', dtype('O'))),
 (15, ('has_param', dtype('O'))),
 (16, ('has_reqtext', dtype('O'))),
 (17, ('num_stars', dtype('float64')))]